import React, { useEffect, useRef, useState } from 'react';
import { X, Download, FileText, Check, ShieldAlert, Building2, Printer, FileDown } from 'lucide-react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { PredictionResult } from '../types';
import { generateQrSvg, suggestedTests } from '../utils/qr';

interface PdfExportModalProps {
  result: PredictionResult;
  onClose: () => void;
}

export const PdfExportModal: React.FC<PdfExportModalProps> = ({ result, onClose }) => {
  const [institutionName, setInstitutionName] = useState('NVIDIA Medical AI Research Institute');
  const [physicianName, setPhysicianName] = useState('Dr. A. Vance, MD (Radiology)');
  const [isGenerating, setIsGenerating] = useState(false);
  const reportRef = useRef<HTMLDivElement | null>(null);

  // ESC closes the modal
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [onClose]);

  const handleDownloadDocx = () => {
    // Word-compatible HTML export (.doc) — no extra dependency needed
    const tests = suggestedTests(result.topDiagnosis);
    const differential = result.diseases.filter((d) => d.probability >= 0.15 && d.disease !== 'No Finding').slice(0, 3);
    const rows = result.diseases
      .slice(0, 6)
      .map((d) => `<tr><td>${d.disease}</td><td>${(d.probability * 100).toFixed(1)}%</td></tr>`)
      .join('');
    const diffRows = differential
      .map((d) => `<li><b>${d.disease}</b> — ${(d.probability * 100).toFixed(1)}% — ${d.description}</li>`)
      .join('');
    const findingItems = result.report.findings.map((f) => `<li>${f}</li>`).join('');
    const recItems = result.report.recommendations.map((r) => `<li>${r}</li>`).join('');
    const testItems = tests.map((t) => `<li>${t}</li>`).join('');

    const html = `
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word">
<head><meta charset="utf-8"><title>MedVision AI Report</title></head>
<body style="font-family: Arial, sans-serif; font-size: 11pt; color: #0f172a;">
  <div style="border-bottom: 2px solid #0f172a; padding-bottom: 12px;">
    <h1 style="margin:0; font-size: 18pt;">${institutionName}</h1>
    <p style="margin:2px 0;">DEPARTMENT OF DIAGNOSTIC RADIOLOGY &amp; IMAGING</p>
    <p style="margin:0; color:#64748b;">Report ID: ${result.report.patientId} | Date: ${result.report.studyDate} | Model: ${result.modelUsed}</p>
  </div>
  <table style="width:100%; border-collapse:collapse; margin:12px 0; font-size:10pt;">
    <tr><td><b>PATIENT ID:</b> ${result.report.patientId}</td><td><b>AGE/SEX:</b> ${result.report.patientAge || 52} / ${result.report.patientSex || 'M'}</td></tr>
    <tr><td><b>SEVERITY:</b> ${result.severity.toUpperCase()} (${result.severityScore}/100)</td><td><b>TOP FINDING:</b> ${result.topDiagnosis} (${(result.topConfidence * 100).toFixed(0)}%)</td></tr>
  </table>
  <h3 style="text-transform:uppercase; font-size:10pt;">Multi-Disease Probabilities</h3>
  <table style="width:60%; border-collapse:collapse; font-size:10pt;" border="1" cellpadding="4"><tr><th>Disease</th><th>Probability</th></tr>${rows}</table>
  <h3 style="text-transform:uppercase; font-size:10pt;">Clinical Indication</h3><p>${result.report.indication}</p>
  <h3 style="text-transform:uppercase; font-size:10pt;">Findings</h3><ul>${findingItems}</ul>
  <h3 style="text-transform:uppercase; font-size:10pt;">Impression</h3><p><b>${result.report.impression}</b></p>
  <h3 style="text-transform:uppercase; font-size:10pt;">Differential Diagnosis</h3><ul>${diffRows || '<li>None above threshold</li>'}</ul>
  <h3 style="text-transform:uppercase; font-size:10pt;">Suggested Confirmatory Tests</h3><ul>${testItems}</ul>
  <h3 style="text-transform:uppercase; font-size:10pt;">Recommendations</h3><ul>${recItems}</ul>
  <p style="color:#b91c1c; font-weight:bold;">CRITICAL DISCLAIMER: NOT FOR CLINICAL DIAGNOSIS.</p>
  <p style="color:#64748b;">Generated by MedVision AI for research and educational benchmarking purposes only.</p>
  <div style="margin-top:24px; border-top: 1px solid #94a3b8; padding-top:8px;">${physicianName} — Verified Radiologist Signature</div>
</body></html>`;

    const blob = new Blob(['\ufeff', html], { type: 'application/msword' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `MedVision_Report_${result.report.patientId}.doc`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPdf = async () => {
    if (!reportRef.current) return;
    setIsGenerating(true);

    try {
      const element = reportRef.current;
      const canvas = await html2canvas(element, {
        scale: 2,
        useCORS: true,
        backgroundColor: '#ffffff',
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      });

      const imgWidth = 210;
      const pageHeight = 297;
      const margin = 8;
      const usableHeight = pageHeight - margin * 2;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;

      // Multi-page pagination: slice the tall canvas into A4 pages
      if (imgHeight <= usableHeight) {
        pdf.addImage(imgData, 'PNG', 0, 0, imgWidth, imgHeight);
      } else {
        let heightLeft = imgHeight;
        let position = 0;
        let page = 0;
        while (heightLeft > 0) {
          if (page > 0) pdf.addPage();
          const sliceH = Math.min(canvas.height * ((usableHeight - (page === 0 ? margin : margin)) / imgHeight), canvas.height);
          const sliceY = (position / imgHeight) * canvas.height;
          const slice = document.createElement('canvas');
          slice.width = canvas.width;
          slice.height = Math.min(sliceH, canvas.height - sliceY);
          const ctx = slice.getContext('2d');
          if (ctx) ctx.drawImage(canvas, 0, sliceY, canvas.width, slice.height, 0, 0, canvas.width, slice.height);
          pdf.addImage(slice.toDataURL('image/png'), 'PNG', 0, page === 0 ? 0 : 0, imgWidth, (slice.height / canvas.height) * imgHeight);
          heightLeft -= (slice.height / canvas.height) * imgHeight;
          position += (slice.height / canvas.height) * imgHeight;
          page += 1;
        }
      }

      pdf.save(`MedVision_Report_${result.report.patientId}.pdf`);
    } catch (err) {
      console.error('PDF Generation failed:', err);
      alert('Failed to generate PDF. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-sm flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-white border border-slate-200 rounded-xl max-w-4xl w-full p-6 space-y-6 max-h-[90vh] flex flex-col shadow-xl text-slate-800">
        {/* Modal Top Bar */}
        <div className="flex items-center justify-between border-b border-slate-100 pb-4">
          <div className="flex items-center gap-2 text-slate-900 font-bold text-base">
            <FileText className="w-5 h-5 text-indigo-600" />
            <span>Hospital Radiology Report Preview</span>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleDownloadDocx}
              className="px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs rounded-md shadow-xs flex items-center gap-2 cursor-pointer transition-colors"
              title="Export as Word document"
            >
              <FileDown className="w-4 h-4" />
              <span className="hidden sm:inline">DOCX</span>
            </button>
            <button
              onClick={handleDownloadPdf}
              disabled={isGenerating}
              className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs rounded-md shadow-xs flex items-center gap-2 cursor-pointer transition-colors disabled:opacity-50"
            >
              <Download className="w-4 h-4" />
              <span>{isGenerating ? 'Rendering...' : 'Download PDF'}</span>
            </button>

            <button
              onClick={onClose}
              className="p-2 text-slate-400 hover:text-slate-700 hover:bg-slate-100 rounded-md transition-colors cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Customization Inputs */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 bg-slate-50 p-3 rounded-lg border border-slate-200 text-xs">
          <div>
            <label className="text-[11px] font-semibold text-slate-600 block mb-1">Institution Name:</label>
            <input
              type="text"
              value={institutionName}
              onChange={(e) => setInstitutionName(e.target.value)}
              className="w-full bg-white border border-slate-300 text-slate-800 px-3 py-1.5 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500 shadow-2xs"
            />
          </div>
          <div>
            <label className="text-[11px] font-semibold text-slate-600 block mb-1">Attending Radiologist:</label>
            <input
              type="text"
              value={physicianName}
              onChange={(e) => setPhysicianName(e.target.value)}
              className="w-full bg-white border border-slate-300 text-slate-800 px-3 py-1.5 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500 shadow-2xs"
            />
          </div>
        </div>

        {/* Printable White Document Canvas Area */}
        <div className="overflow-y-auto flex-1 bg-slate-100 p-4 rounded-lg border border-slate-200 flex justify-center">
          <div
            ref={reportRef}
            className="w-[210mm] min-h-[297mm] bg-white text-slate-900 p-8 shadow-2xl space-y-6 font-sans text-xs border border-slate-200 text-left"
            style={{ boxSizing: 'border-box' }}
          >
            {/* Hospital Header */}
            <div className="border-b-2 border-slate-900 pb-4 flex justify-between items-start">
              <div>
                <h1 className="text-lg font-bold uppercase text-slate-900 tracking-tight">{institutionName}</h1>
                <p className="text-[11px] text-slate-600 font-semibold">DEPARTMENT OF DIAGNOSTIC RADIOLOGY &amp; IMAGING</p>
                <p className="text-[10px] text-slate-500">Center for Explainable Medical Artificial Intelligence</p>
              </div>

              <div className="text-right text-[10px] font-mono text-slate-600">
                <div className="font-bold text-slate-900 text-xs">REPORT ID: {result.report.patientId}</div>
                <div>DATE: {result.report.studyDate}</div>
                <div>MODEL: {result.modelUsed}</div>
              </div>
            </div>

            {/* Patient Info Table */}
            <div className="grid grid-cols-4 gap-2 bg-slate-100 p-3 rounded border border-slate-300 font-mono text-[11px]">
              <div>
                <span className="text-slate-500 block text-[9px]">PATIENT ID</span>
                <span className="font-bold">{result.report.patientId}</span>
              </div>
              <div>
                <span className="text-slate-500 block text-[9px]">AGE / SEX</span>
                <span>{result.report.patientAge || 52} Y.O. / {result.report.patientSex || 'M'}</span>
              </div>
              <div>
                <span className="text-slate-500 block text-[9px]">SEVERITY</span>
                <span className="font-bold text-rose-700">{result.severity.toUpperCase()} ({result.severityScore}/100)</span>
              </div>
              <div>
                <span className="text-slate-500 block text-[9px]">TOP FINDING</span>
                <span className="font-bold text-blue-800">{result.topDiagnosis} ({(result.topConfidence * 100).toFixed(0)}%)</span>
              </div>
            </div>

            {/* Images Grid (X-ray + Grad-CAM) */}
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1 text-center">
                <span className="text-[10px] font-bold text-slate-700 uppercase">Chest Radiograph (PA View)</span>
                <div className="w-full aspect-square bg-slate-900 rounded border border-slate-300 overflow-hidden flex items-center justify-center">
                  <img src={result.originalImageUrl} alt="Xray" className="h-full object-contain" />
                </div>
              </div>

              <div className="space-y-1 text-center">
                <span className="text-[10px] font-bold text-rose-800 uppercase">Grad-CAM Feature Activation Map</span>
                <div className="w-full aspect-square bg-slate-900 rounded border border-slate-300 overflow-hidden flex items-center justify-center">
                  <img src={result.heatmapOverlayUrl} alt="GradCAM" className="h-full object-contain" />
                </div>
              </div>
            </div>

            {/* Top Pathology Probabilities Table */}
            <div className="space-y-1">
              <h3 className="font-bold uppercase text-[11px] text-slate-800 border-b border-slate-300 pb-0.5">
                Multi-Disease Machine Learning Probabilities
              </h3>
              <div className="grid grid-cols-2 gap-x-4 gap-y-1 text-[10px] font-mono pt-1">
                {result.diseases.slice(0, 6).map((d) => (
                  <div key={d.disease} className="flex justify-between border-b border-slate-100 py-0.5">
                    <span className="text-slate-700">{d.disease}:</span>
                    <span className={d.probability >= 0.5 ? 'font-bold text-rose-700' : 'text-slate-600'}>
                      {(d.probability * 100).toFixed(1)}%
                    </span>
                  </div>
                ))}
              </div>
            </div>

            {/* Report Content */}
            <div className="space-y-3 leading-relaxed text-slate-800 text-[11px]">
              <div>
                <strong className="text-slate-900 uppercase">CLINICAL INDICATION: </strong>
                <span>{result.report.indication}</span>
              </div>

              <div>
                <strong className="text-slate-900 uppercase">EXAM TECHNIQUE: </strong>
                <span>{result.report.technique}</span>
              </div>

              <div>
                <strong className="text-slate-900 uppercase block mb-0.5">FINDINGS:</strong>
                <ul className="list-disc list-inside space-y-0.5 text-slate-700">
                  {result.report.findings.map((f, i) => (
                    <li key={i}>{f}</li>
                  ))}
                </ul>
              </div>

              <div className="bg-slate-50 p-2.5 rounded border border-slate-300">
                <strong className="text-slate-900 uppercase block mb-0.5">IMPRESSION:</strong>
                <p className="font-bold text-slate-900 whitespace-pre-line">{result.report.impression}</p>
              </div>

              <div>
                <strong className="text-slate-900 uppercase block mb-0.5">RECOMMENDATIONS:</strong>
                <ul className="list-disc list-inside space-y-0.5 text-slate-700">
                  {result.report.recommendations.map((r, i) => (
                    <li key={i}>{r}</li>
                  ))}
                </ul>
              </div>
            </div>

            {/* Differential diagnosis strip */}
            <div className="space-y-1">
              <h3 className="font-bold uppercase text-[11px] text-slate-800 border-b border-slate-300 pb-0.5">
                Differential Diagnosis
              </h3>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-2 pt-1">
                {result.diseases.filter((d) => d.probability >= 0.15 && d.disease !== 'No Finding').slice(0, 3).map((d) => (
                  <div key={d.disease} className="border border-slate-300 rounded p-2">
                    <div className="flex justify-between">
                      <span className="font-bold text-slate-800">{d.disease}</span>
                      <span className="font-mono font-bold text-sky-800">{(d.probability * 100).toFixed(1)}%</span>
                    </div>
                    <p className="text-[9px] text-slate-500 mt-0.5">{d.description}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Signature & Disclaimer */}
            <div className="pt-4 border-t border-slate-300 flex justify-between items-end text-[10px]">
              <div className="space-y-1 max-w-md">
                <p className="font-bold text-rose-800">
                  CRITICAL DISCLAIMER: NOT FOR CLINICAL DIAGNOSIS.
                </p>
                <p className="text-slate-500">
                  This report was generated automatically by MedVision AI for research and educational benchmarking purposes only.
                </p>
              </div>

              <div className="flex items-end gap-4">
                <div className="text-center">
                  <img src={generateQrSvg(result.report.patientId, 21, 64)} alt="Verification QR" className="w-14 h-14 border border-slate-300 rounded bg-white p-0.5" />
                  <p className="text-[8px] font-mono text-slate-500 mt-0.5">VERIFY · {result.report.patientId}</p>
                </div>
                <div className="text-right border-t border-slate-400 pt-1 w-44">
                  <div className="font-bold text-slate-900">{physicianName}</div>
                  <div className="text-slate-500">Verified Radiologist Signature</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
