import {
  ActivityEvent,
  AppNotification,
  DashboardStats,
  DatasetInfo,
  HubModel,
  PatientDetail,
  PatientRecord,
  SessionUser,
  TrainingRun,
} from '../types';

export const DEFAULT_USER: SessionUser = {
  name: 'Dr. Ayesha Vance',
  initials: 'AV',
  role: 'Radiologist',
  department: 'Diagnostic Radiology',
  lastActive: 'Online',
};

export const AVAILABLE_ROLES: SessionUser[] = [
  { name: 'Dr. Ayesha Vance', initials: 'AV', role: 'Radiologist', department: 'Diagnostic Radiology', lastActive: 'Online' },
  { name: 'Dr. Marcus Hale', initials: 'MH', role: 'Doctor', department: 'Pulmonology', lastActive: 'Online' },
  { name: 'Dr. Priya Natarajan', initials: 'PN', role: 'Researcher', department: 'AI Research Lab', lastActive: '2h ago' },
  { name: 'Sara Kim', initials: 'SK', role: 'Student', department: 'Medical School', lastActive: '5h ago' },
  { name: 'System Admin', initials: 'SA', role: 'Admin', department: 'IT & MLOps', lastActive: 'Online' },
];

export const SEED_NOTIFICATIONS: AppNotification[] = [
  { id: 'n1', kind: 'critical', title: 'Emergency case flagged', body: 'PAT-991283 — Bilateral pneumothorax detected (93% confidence). Radiologist review required within 30 min.', time: '2m ago', read: false },
  { id: 'n2', kind: 'success', title: 'Report completed', body: 'AI radiology report for PAT-883921 (Pneumonia) generated by Gemini 3.6 Flash.', time: '14m ago', read: false },
  { id: 'n3', kind: 'warning', title: 'GPU thermal warning', body: 'H100 #3 at 88°C. Fan curve auto-adjusted. Throughput preserved.', time: '41m ago', read: false },
  { id: 'n4', kind: 'info', title: 'Training run finished', body: 'swin-b-mixed-precision-amp reached val AUROC 0.889 (best checkpoint saved).', time: '1h ago', read: true },
  { id: 'n5', kind: 'info', title: 'Model deployed', body: 'EfficientNet-B3 v2.4.1 promoted to Production in the Model Registry.', time: '3h ago', read: true },
  { id: 'n6', kind: 'warning', title: 'Dataset drift detected', body: 'CheXpert val distribution drifted 2.1% vs training. Re-calibration suggested.', time: '6h ago', read: true },
];

export const ACTIVITY_FEED: ActivityEvent[] = [
  { id: 'a1', type: 'scan', actor: 'DenseNet-121', action: 'completed scan', detail: 'PAT-991283 · Bilateral Pneumothorax', time: '2m ago', severity: 'Critical' },
  { id: 'a2', type: 'report', actor: 'Gemini 3.6 Flash', action: 'generated report', detail: 'PAT-883921 · Pneumonia (High)', time: '14m ago', severity: 'High' },
  { id: 'a3', type: 'patient', actor: 'Front Desk', action: 'admitted patient', detail: 'PAT-552014 · ICU admission', time: '26m ago' },
  { id: 'a4', type: 'training', actor: 'Swin-B', action: 'epoch 45/45', detail: 'val AUROC 0.889 · val loss 0.108', time: '1h ago' },
  { id: 'a5', type: 'model', actor: 'MLflow', action: 'promoted model', detail: 'EfficientNet-B3 v2.4.1 → Production', time: '3h ago' },
  { id: 'a6', type: 'system', actor: 'AutoScaler', action: 'scaled GPU pool', detail: '+2 × A100 workers (queue backlog)', time: '4h ago' },
  { id: 'a7', type: 'scan', actor: 'ViT-B/16', action: 'completed scan', detail: 'PAT-334182 · Cardiomegaly (Moderate)', time: '5h ago', severity: 'Moderate' },
  { id: 'a8', type: 'report', actor: 'Gemini 3.6 Flash', action: 'summarized study', detail: 'PAT-100293 · Normal study', time: '7h ago', severity: 'Low' },
];

export const DASHBOARD_STATS: DashboardStats = {
  aiStatus: 'online',
  todayScans: 128,
  pendingReports: 14,
  emergencyCases: 3,
  totalPatients: 8420,
  aiAccuracy: 94.8,
  avgLatencyMs: 21.4,
  activeModels: 5,
  queuedPredictions: 7,
  weeklyTrend: [
    { day: 'Mon', scans: 96, reports: 88, aiAccuracy: 93.6 },
    { day: 'Tue', scans: 112, reports: 104, aiAccuracy: 94.2 },
    { day: 'Wed', scans: 134, reports: 122, aiAccuracy: 94.9 },
    { day: 'Thu', scans: 121, reports: 117, aiAccuracy: 94.4 },
    { day: 'Fri', scans: 148, reports: 139, aiAccuracy: 95.6 },
    { day: 'Sat', scans: 88, reports: 82, aiAccuracy: 94.1 },
    { day: 'Sun', scans: 71, reports: 68, aiAccuracy: 95.2 },
  ],
  monthlyTrend: [
    { month: 'Feb', scans: 2150 },
    { month: 'Mar', scans: 2480 },
    { month: 'Apr', scans: 2310 },
    { month: 'May', scans: 2890 },
    { month: 'Jun', scans: 3120 },
    { month: 'Jul', scans: 3480 },
  ],
  diseaseStats: [
    { disease: 'Pneumonia', count: 1240, color: '#6366f1' },
    { disease: 'Lung Opacity', count: 980, color: '#38bdf8' },
    { disease: 'Atelectasis', count: 640, color: '#10b981' },
    { disease: 'Pleural Effusion', count: 520, color: '#f59e0b' },
    { disease: 'Cardiomegaly', count: 310, color: '#8b5cf6' },
    { disease: 'Pneumothorax', count: 210, color: '#ec4899' },
    { disease: 'No Finding', count: 1850, color: '#94a3b8' },
  ],
  severityDistribution: [
    { name: 'Low', value: 42, color: '#10b981' },
    { name: 'Moderate', value: 31, color: '#f59e0b' },
    { name: 'High', value: 19, color: '#f97316' },
    { name: 'Critical', value: 8, color: '#ef4444' },
  ],
  systemHealth: [
    { component: 'GPU (H100 ×4)', usage: 72, status: 'healthy' },
    { component: 'CPU', usage: 41, status: 'healthy' },
    { component: 'Memory', usage: 63, status: 'healthy' },
    { component: 'Inference Queue', usage: 18, status: 'healthy' },
    { component: 'Gemini API', usage: 34, status: 'healthy' },
    { component: 'Storage', usage: 78, status: 'warning' },
  ],
  queue: [
    { id: 'q1', patient: 'PAT-991283', study: 'CXR PA (Emergency)', model: 'Swin-B', etaSec: 8, progress: 62 },
    { id: 'q2', patient: 'PAT-552014', study: 'CXR AP (ICU)', model: 'EfficientNet-B3', etaSec: 14, progress: 31 },
    { id: 'q3', patient: 'PAT-220981', study: 'CXR PA (Routine)', model: 'DenseNet-121', etaSec: 22, progress: 9 },
  ],
};

const BASE_PATIENTS: PatientRecord[] = [
  { id: 'PAT-883921', name: 'John Doe', age: 54, sex: 'M', bloodGroup: 'O+', phone: '+1 (555) 012-3344', email: 'j.doe@medmail.io', department: 'Pulmonology', status: 'Admitted', admissionDate: '2026-07-28', lastVisit: '2026-08-01', medicalHistory: ['Hypertension', 'T2 Diabetes'], allergies: ['Penicillin'], medications: ['Metformin 500mg', 'Lisinopril 10mg'], topDiagnosis: 'Pneumonia', lastSeverity: 'High', riskScore: 82, avatarHue: 250 },
  { id: 'PAT-772109', name: 'Grace Liu', age: 62, sex: 'F', bloodGroup: 'A−', phone: '+1 (555) 081-7765', email: 'g.liu@medmail.io', department: 'Critical Care', status: 'Critical', admissionDate: '2026-07-29', lastVisit: '2026-08-01', medicalHistory: ['COPD', 'Asthma'], allergies: ['Sulfa drugs'], medications: ['Salbutamol MDI', 'Prednisone 5mg'], topDiagnosis: 'COVID-19 Pneumonia', lastSeverity: 'Critical', riskScore: 91, avatarHue: 330 },
  { id: 'PAT-334182', name: 'Robert Chen', age: 68, sex: 'M', bloodGroup: 'B+', phone: '+1 (555) 044-2210', email: 'r.chen@medmail.io', department: 'Cardiology', status: 'Outpatient', admissionDate: '2026-06-12', lastVisit: '2026-07-30', medicalHistory: ['CHF', 'Atrial Fibrillation'], allergies: ['None known'], medications: ['Furosemide 40mg', 'Warfarin 5mg'], topDiagnosis: 'Cardiomegaly', lastSeverity: 'Moderate', riskScore: 68, avatarHue: 210 },
  { id: 'PAT-100293', name: 'Elena Rodriguez', age: 31, sex: 'F', bloodGroup: 'AB+', phone: '+1 (555) 099-8834', email: 'e.rod@medmail.io', department: 'Occupational Health', status: 'Discharged', admissionDate: '2026-05-03', lastVisit: '2026-07-24', medicalHistory: ['None'], allergies: ['Latex'], medications: ['None'], topDiagnosis: 'No Finding', lastSeverity: 'Low', riskScore: 6, avatarHue: 160 },
  { id: 'PAT-552014', name: 'Omar Farouk', age: 47, sex: 'M', bloodGroup: 'O−', phone: '+1 (555) 023-1188', email: 'o.farouk@medmail.io', department: 'ICU', status: 'ICU', admissionDate: '2026-07-31', lastVisit: '2026-08-01', medicalHistory: ['Cirrhosis', 'Portal HTN'], allergies: ['Codeine'], medications: ['Spironolactone 25mg', 'Lactulose'], topDiagnosis: 'Pleural Effusion', lastSeverity: 'High', riskScore: 78, avatarHue: 30 },
  { id: 'PAT-220981', name: 'Hannah Weiss', age: 24, sex: 'F', bloodGroup: 'A+', phone: '+1 (555) 067-5523', email: 'h.weiss@medmail.io', department: 'Emergency', status: 'Outpatient', admissionDate: '2026-07-15', lastVisit: '2026-07-31', medicalHistory: ['None'], allergies: ['None known'], medications: ['None'], topDiagnosis: 'Pneumothorax', lastSeverity: 'High', riskScore: 74, avatarHue: 120 },
  { id: 'PAT-661120', name: 'Samuel Okafor', age: 59, sex: 'M', bloodGroup: 'B−', phone: '+1 (555) 031-4470', email: 's.okafor@medmail.io', department: 'Oncology', status: 'Admitted', admissionDate: '2026-07-20', lastVisit: '2026-08-01', medicalHistory: ['Lung Ca (Stage II)', 'HTN'], allergies: ['Iodine contrast'], medications: ['Carboplatin', 'Paclitaxel'], topDiagnosis: 'Lung Opacity', lastSeverity: 'Moderate', riskScore: 64, avatarHue: 280 },
  { id: 'PAT-447381', name: 'Maria Santos', age: 71, sex: 'F', bloodGroup: 'O+', phone: '+1 (555) 055-9921', email: 'm.santos@medmail.io', department: 'Geriatrics', status: 'Admitted', admissionDate: '2026-07-25', lastVisit: '2026-08-01', medicalHistory: ['Dementia', 'CHF'], allergies: ['Aspirin'], medications: ['Donepezil 10mg', 'Digoxin 0.125mg'], topDiagnosis: 'Edema', lastSeverity: 'Moderate', riskScore: 59, avatarHue: 40 },
];

export const PATIENTS: PatientRecord[] = BASE_PATIENTS;

const VISITS_BY_ID: Record<string, PatientDetail['visits']> = {
  'PAT-883921': [
    { id: 'v1', date: '2026-08-01', type: 'X-Ray', findings: 'Right lower lobe consolidation with air bronchograms. Trace reactive effusion.', severity: 'High', physician: 'Dr. A. Vance', reports: ['CXR PA #88412', 'AI Report #A88412'] },
    { id: 'v2', date: '2026-07-18', type: 'Consultation', findings: 'Productive cough ×4 days, fever 38.9°C. WBC 14.2.', severity: 'Moderate', physician: 'Dr. M. Hale', reports: ['CBC Panel'] },
    { id: 'v3', date: '2026-06-30', type: 'Lab', findings: 'HbA1c 7.1% — diabetic control suboptimal.', severity: 'Low', physician: 'Dr. M. Hale', reports: ['HbA1c Report'] },
  ],
  'PAT-772109': [
    { id: 'v1', date: '2026-08-01', type: 'X-Ray', findings: 'Bilateral peripheral ground-glass opacities. SpO2 89% on room air.', severity: 'Critical', physician: 'Dr. A. Vance', reports: ['CXR AP #88501', 'AI Report #A88501'] },
    { id: 'v2', date: '2026-07-29', type: 'Lab', findings: 'RT-PCR positive for SARS-CoV-2. D-dimer 1.8 mg/L.', severity: 'Critical', physician: 'Dr. M. Hale', reports: ['PCR Result', 'Coagulation Panel'] },
  ],
  'PAT-334182': [
    { id: 'v1', date: '2026-07-30', type: 'X-Ray', findings: 'CTR 0.58, prominent LV apex, mild cephalization.', severity: 'Moderate', physician: 'Dr. A. Vance', reports: ['CXR PA #88370', 'AI Report #A88370'] },
    { id: 'v2', date: '2026-06-12', type: 'Consultation', findings: 'NYHA II exertional dyspnea. Echo EF 38%.', severity: 'Moderate', physician: 'Dr. R. Patel', reports: ['Echocardiogram'] },
  ],
  'PAT-100293': [
    { id: 'v1', date: '2026-07-24', type: 'X-Ray', findings: 'Unremarkable. Clear lung fields, normal cardiac silhouette.', severity: 'Low', physician: 'Dr. A. Vance', reports: ['CXR PA #88290', 'AI Report #A88290'] },
  ],
  'PAT-552014': [
    { id: 'v1', date: '2026-08-01', type: 'X-Ray', findings: 'Moderate right pleural effusion with blunted costophrenic angle.', severity: 'High', physician: 'Dr. A. Vance', reports: ['CXR AP #88522', 'AI Report #A88522'] },
    { id: 'v2', date: '2026-07-31', type: 'Lab', findings: 'Albumin 2.1 g/dL, PT/INR elevated.', severity: 'High', physician: 'Dr. M. Hale', reports: ['LFT Panel'] },
  ],
  'PAT-220981': [
    { id: 'v1', date: '2026-07-31', type: 'X-Ray', findings: 'Left apical pneumothorax ~15%. Visceral pleural line visible.', severity: 'High', physician: 'Dr. A. Vance', reports: ['CXR PA #88490', 'AI Report #A88490'] },
  ],
  'PAT-661120': [
    { id: 'v1', date: '2026-08-01', type: 'CT', findings: 'Peripheral lung nodule 2.4cm RLL with spiculation. Stage IIa.', severity: 'Moderate', physician: 'Dr. R. Patel', reports: ['CT Chest #88112'] },
    { id: 'v2', date: '2026-07-20', type: 'X-Ray', findings: 'Focal opacity right mid-zone; central lesion suspected.', severity: 'Moderate', physician: 'Dr. A. Vance', reports: ['CXR PA #88110', 'AI Report #A88110'] },
  ],
  'PAT-447381': [
    { id: 'v1', date: '2026-08-01', type: 'X-Ray', findings: 'Mild interstitial edema, Kerley B lines, small bilateral effusions.', severity: 'Moderate', physician: 'Dr. A. Vance', reports: ['CXR PA #88540', 'AI Report #A88540'] },
    { id: 'v2', date: '2026-07-25', type: 'Consultation', findings: 'Weight gain 3kg, orthopnea, pedal edema.', severity: 'Moderate', physician: 'Dr. R. Patel', reports: ['Cardiac Consult'] },
  ],
};

const TIMELINES: Record<string, PatientDetail['timeline']> = {
  'PAT-883921': [
    { date: '2026-08-01', title: 'AI Report Generated', detail: 'Pneumonia (94% confidence) — High severity. Gemini 3.6 Flash synthesis complete.', kind: 'report' },
    { date: '2026-08-01', title: 'Chest X-Ray Performed', detail: 'PA upright. Right lower lobe consolidation.', kind: 'visit' },
    { date: '2026-07-18', title: 'Primary Consult', detail: 'Started empiric amoxicillin-clavulanate.', kind: 'visit' },
    { date: '2026-06-30', title: 'HbA1c Lab', detail: '7.1% — medication review.', kind: 'lab' },
    { date: '2026-06-01', title: 'Medication Adjusted', detail: 'Metformin dose increased to 500mg BID.', kind: 'medication' },
  ],
  'PAT-772109': [
    { date: '2026-08-01', title: 'AI Report Generated', detail: 'COVID-19 pneumonitis (91%) — Critical. High-flow O2 initiated.', kind: 'report' },
    { date: '2026-08-01', title: 'Chest X-Ray Performed', detail: 'Portable AP. Bilateral GGOs.', kind: 'visit' },
    { date: '2026-07-29', title: 'RT-PCR Positive', detail: 'SARS-CoV-2 detected. Started dexamethasone.', kind: 'lab' },
    { date: '2026-07-29', title: 'Admitted to ICU', detail: 'SpO2 89%, tachypnea.', kind: 'visit' },
  ],
  'PAT-334182': [
    { date: '2026-07-30', title: 'AI Report Generated', detail: 'Cardiomegaly (96%) — Moderate. Echocardiogram recommended.', kind: 'report' },
    { date: '2026-07-30', title: 'Chest X-Ray Performed', detail: 'CTR 0.58.', kind: 'visit' },
    { date: '2026-06-12', title: 'Cardiology Consult', detail: 'EF 38%. Started sacubitril/valsartan.', kind: 'visit' },
  ],
  'PAT-100293': [
    { date: '2026-07-24', title: 'AI Report Generated', detail: 'No Finding (97%) — Low severity. No follow-up needed.', kind: 'report' },
    { date: '2026-07-24', title: 'Screening X-Ray', detail: 'Pre-employment PA + Lateral.', kind: 'visit' },
  ],
  'PAT-552014': [
    { date: '2026-08-01', title: 'AI Report Generated', detail: 'Pleural Effusion (89%) — High. Thoracentesis scheduled.', kind: 'report' },
    { date: '2026-08-01', title: 'Chest X-Ray Performed', detail: 'AP portable, ICU.', kind: 'visit' },
    { date: '2026-07-31', title: 'Transferred to ICU', detail: 'Hypotension, encephalopathy.', kind: 'visit' },
  ],
  'PAT-220981': [
    { date: '2026-07-31', title: 'AI Report Generated', detail: 'Pneumothorax (87%) — High. Chest tube placed.', kind: 'report' },
    { date: '2026-07-31', title: 'Emergency X-Ray', detail: 'Left apical PTX ~15%.', kind: 'visit' },
  ],
  'PAT-661120': [
    { date: '2026-08-01', title: 'CT Chest Performed', detail: '2.4cm spiculated RLL nodule.', kind: 'visit' },
    { date: '2026-07-20', title: 'AI Report Generated', detail: 'Lung Opacity (88%) — Moderate.', kind: 'report' },
    { date: '2026-07-20', title: 'Chest X-Ray Performed', detail: 'Focal mid-zone opacity.', kind: 'visit' },
  ],
  'PAT-447381': [
    { date: '2026-08-01', title: 'AI Report Generated', detail: 'Edema (84%) — Moderate. Diuretic adjusted.', kind: 'report' },
    { date: '2026-08-01', title: 'Chest X-Ray Performed', detail: 'Mild congestion, Kerley B lines.', kind: 'visit' },
    { date: '2026-07-25', title: 'Cardiac Consult', detail: 'Weight +3kg, orthopnea.', kind: 'visit' },
  ],
};

export function getPatientDetail(id: string): PatientDetail | null {
  const base = BASE_PATIENTS.find((p) => p.id === id);
  if (!base) return null;
  return {
    ...base,
    timeline: TIMELINES[id] ?? [],
    visits: VISITS_BY_ID[id] ?? [],
    previousReports: (VISITS_BY_ID[id] ?? [])
      .flatMap((v) => v.reports)
      .slice(0, 5),
    followUps: [
      { date: '2026-08-15', note: 'Follow-up CXR to confirm radiographic resolution', completed: false },
      { date: '2026-08-08', note: 'Sputum culture review + CBC', completed: true },
      { date: '2026-08-01', note: 'Initial AI-assisted interpretation', completed: true },
    ],
  };
}

export const HUB_MODELS: HubModel[] = [
  { id: 'resnet50', name: 'ResNet-50', family: 'CNN', task: 'Classification', framework: 'PyTorch', accuracy: 88.7, precision: 0.87, recall: 0.86, specificity: 0.91, sensitivity: 0.86, f1: 0.865, auroc: 0.852, parameters: '25.6M', flops: '4.1G', size: '98MB', latencyMs: 22, color: '#6366f1', description: 'Residual learning backbone with 50 layers — the classic deep CNN for transfer learning.', bestFor: 'Balanced baseline & transfer-learning fine-tuning', deployed: true },
  { id: 'densenet121', name: 'DenseNet-121', family: 'CNN', task: 'Classification', framework: 'PyTorch', accuracy: 89.4, precision: 0.88, recall: 0.87, specificity: 0.92, sensitivity: 0.87, f1: 0.875, auroc: 0.861, parameters: '7.0M', flops: '2.9G', size: '27MB', latencyMs: 18, color: '#818cf8', description: 'Dense connectivity & feature reuse — the CheXNet benchmark architecture.', bestFor: 'Multi-label thoracic pathology detection', deployed: true },
  { id: 'efficientnet_b3', name: 'EfficientNet-B3', family: 'CNN', task: 'Classification', framework: 'PyTorch', accuracy: 91.2, precision: 0.90, recall: 0.89, specificity: 0.93, sensitivity: 0.89, f1: 0.895, auroc: 0.878, parameters: '12.2M', flops: '1.8G', size: '47MB', latencyMs: 24, color: '#38bdf8', description: 'Compound-scaled depthwise-separable CNN with excellent parameter efficiency.', bestFor: 'Edge & mobile inference with high accuracy', deployed: true },
  { id: 'mobilenet_v3', name: 'MobileNet-V3', family: 'CNN', task: 'Classification', framework: 'PyTorch', accuracy: 87.1, precision: 0.85, recall: 0.84, specificity: 0.90, sensitivity: 0.84, f1: 0.845, auroc: 0.838, parameters: '4.2M', flops: '0.2G', size: '16MB', latencyMs: 9, color: '#22d3ee', description: 'Neural-architecture-search-optimized mobile CNN using hard-swish activations.', bestFor: 'On-device triage & low-latency screening', deployed: false },
  { id: 'convnext_base', name: 'ConvNeXt-Base', family: 'CNN', task: 'Classification', framework: 'PyTorch', accuracy: 92.8, precision: 0.92, recall: 0.91, specificity: 0.94, sensitivity: 0.91, f1: 0.915, auroc: 0.895, parameters: '88.5M', flops: '15.4G', size: '338MB', latencyMs: 38, color: '#10b981', description: 'Modernized pure CNN adopting transformer design principles (7×7 depthwise, LayerNorm, GELU).', bestFor: 'High-precision GPU-based clinical screening', deployed: true },
  { id: 'vit_b', name: 'Vision Transformer (ViT-B/16)', family: 'Transformer', task: 'Classification', framework: 'PyTorch', accuracy: 92.1, precision: 0.91, recall: 0.90, specificity: 0.93, sensitivity: 0.90, f1: 0.905, auroc: 0.888, parameters: '86.6M', flops: '17.6G', size: '331MB', latencyMs: 42, color: '#8b5cf6', description: 'Pure self-attention over 16×16 patches — global receptive field without convolution.', bestFor: 'Attention-rollout visualization & global context', deployed: false },
  { id: 'swin_b', name: 'Swin Transformer (Swin-B)', family: 'Transformer', task: 'Classification', framework: 'PyTorch', accuracy: 93.5, precision: 0.93, recall: 0.92, specificity: 0.95, sensitivity: 0.92, f1: 0.925, auroc: 0.902, parameters: '88.0M', flops: '15.4G', size: '336MB', latencyMs: 45, color: '#a78bfa', description: 'Hierarchical shifted-window attention capturing multi-scale thoracic dependencies.', bestFor: 'Complex multi-focal pathologies (GGO, miliary TB)', deployed: true },
  { id: 'yolov8', name: 'YOLOv8', family: 'Detection', task: 'Detection', framework: 'Ultralytics', accuracy: 90.4, precision: 0.89, recall: 0.88, specificity: 0.92, sensitivity: 0.88, f1: 0.885, auroc: 0.874, parameters: '11.2M', flops: '8.7G', size: '44MB', latencyMs: 12, color: '#f59e0b', description: 'Anchor-free one-stage detector with C2f backbone — the industry default for object detection.', bestFor: 'Localizing nodules, masses & devices', deployed: true },
  { id: 'yolov11', name: 'YOLOv11', family: 'Detection', task: 'Detection', framework: 'Ultralytics', accuracy: 91.8, precision: 0.91, recall: 0.90, specificity: 0.93, sensitivity: 0.90, f1: 0.905, auroc: 0.891, parameters: '25.3M', flops: '9.1G', size: '98MB', latencyMs: 14, color: '#fbbf24', description: 'Next-gen YOLO with C3k2 blocks, C2PSA attention & MAB bottleneck — SOTA speed/accuracy.', bestFor: 'Real-time emergency detection pipelines', deployed: false },
  { id: 'faster_rcnn', name: 'Faster R-CNN', family: 'Detection', task: 'Detection', framework: 'PyTorch', accuracy: 89.7, precision: 0.90, recall: 0.87, specificity: 0.94, sensitivity: 0.87, f1: 0.885, auroc: 0.879, parameters: '41.3M', flops: '134G', size: '158MB', latencyMs: 96, color: '#f97316', description: 'Two-stage Region Proposal Network detector — high precision for small pathology.', bestFor: 'Small-nodule detection with accuracy priority', deployed: false },
  { id: 'unet', name: 'U-Net', family: 'Segmentation', task: 'Segmentation', framework: 'PyTorch', accuracy: 91.0, precision: 0.90, recall: 0.89, specificity: 0.92, sensitivity: 0.89, f1: 0.895, auroc: 0.883, parameters: '31.0M', flops: '57G', size: '118MB', latencyMs: 34, color: '#ec4899', description: 'Encoder-decoder with skip connections — the gold standard for medical segmentation.', bestFor: 'Lung field & lesion boundary segmentation', deployed: true },
  { id: 'attention_unet', name: 'Attention U-Net', family: 'Segmentation', task: 'Segmentation', framework: 'PyTorch', accuracy: 91.9, precision: 0.91, recall: 0.90, specificity: 0.93, sensitivity: 0.90, f1: 0.905, auroc: 0.894, parameters: '34.9M', flops: '61G', size: '133MB', latencyMs: 38, color: '#f472b6', description: 'U-Net + attention gates that suppress irrelevant background features.', bestFor: 'Organ-aware segmentation with soft attention', deployed: false },
  { id: 'deeplabv3', name: 'DeepLabV3+', family: 'Segmentation', task: 'Segmentation', framework: 'PyTorch', accuracy: 92.4, precision: 0.92, recall: 0.91, specificity: 0.94, sensitivity: 0.91, f1: 0.915, auroc: 0.897, parameters: '54.7M', flops: '76G', size: '209MB', latencyMs: 52, color: '#fb7185', description: 'Atrous-convolution pyramid pooling with encoder-decoder refinement.', bestFor: 'High-fidelity multi-class tissue segmentation', deployed: false },
  { id: 'xgboost', name: 'XGBoost', family: 'Traditional ML', task: 'Regression', framework: 'XGBoost', accuracy: 85.6, precision: 0.84, recall: 0.83, specificity: 0.88, sensitivity: 0.83, f1: 0.835, auroc: 0.821, parameters: '—', flops: '—', size: '8MB', latencyMs: 1, color: '#34d399', description: 'Gradient-boosted decision trees with regularization — tabular risk & severity scoring.', bestFor: 'Clinical risk scores & tabular triage', deployed: true },
  { id: 'lightgbm', name: 'LightGBM', family: 'Traditional ML', task: 'Regression', framework: 'LightGBM', accuracy: 85.1, precision: 0.83, recall: 0.83, specificity: 0.87, sensitivity: 0.83, f1: 0.83, auroc: 0.816, parameters: '—', flops: '—', size: '6MB', latencyMs: 1, color: '#4ade80', description: 'Leaf-wise histogram boosting — extremely fast training on large clinical tables.', bestFor: 'High-throughput tabular inference', deployed: false },
  { id: 'random_forest', name: 'Random Forest', family: 'Traditional ML', task: 'Regression', framework: 'scikit-learn', accuracy: 83.9, precision: 0.82, recall: 0.81, specificity: 0.86, sensitivity: 0.81, f1: 0.815, auroc: 0.801, parameters: '—', flops: '—', size: '12MB', latencyMs: 2, color: '#2dd4bf', description: 'Bagged decision forest with built-in feature importance & uncertainty via OOB.', bestFor: 'Interpretable baseline & feature importance', deployed: false },
  { id: 'voting_ensemble', name: 'Stacked Ensemble (Voting)', family: 'Ensemble', task: 'Classification', framework: 'scikit-learn', accuracy: 94.1, precision: 0.94, recall: 0.93, specificity: 0.96, sensitivity: 0.93, f1: 0.935, auroc: 0.916, parameters: '—', flops: '—', size: '64MB', latencyMs: 8, color: '#c084fc', description: 'Soft-voting stack of DenseNet-121 + EfficientNet-B3 + Swin-B with meta-learner.', bestFor: 'Production deployment with maximum robustness', deployed: true },
];

export const DATASETS: DatasetInfo[] = [
  { id: 'nih14', name: 'NIH ChestX-ray14', task: 'Multi-label', images: 112120, labels: 14, classes: ['Atelectasis', 'Cardiomegaly', 'Effusion', 'Infiltration', 'Mass', 'Nodule', 'Pneumonia', 'Pneumothorax', 'Consolidation', 'Edema', 'Emphysema', 'Fibrosis', 'Pleural Thickening', 'Hernia'], sizeGb: '42.3', missingLabels: 1280, duplicates: 96, trainSplit: 70, valSplit: 15, testSplit: 15, source: 'NIH Clinical Center', format: 'PNG / CSV labels', description: 'Largest public chest X-ray dataset with 14 pathology labels from 30,805 unique patients.', color: '#6366f1' },
  { id: 'chexpert', name: 'CheXpert', task: 'Multi-label', images: 224316, labels: 14, sizeGb: '83.1', classes: ['Enlarged Cardiomediastinum', 'Cardiomegaly', 'Lung Opacity', 'Lung Lesion', 'Edema', 'Consolidation', 'Pneumonia', 'Atelectasis', 'Pneumothorax', 'Pleural Effusion', 'Pleural Other', 'Fracture', 'Support Devices', 'No Finding'], missingLabels: 54210, duplicates: 140, trainSplit: 80, valSplit: 10, testSplit: 10, source: 'Stanford ML Group', format: 'JPG / CSVs', description: 'Stanford benchmark with labeler-uncertainty handling (UMLS extraction).', color: '#38bdf8' },
  { id: 'mimic', name: 'MIMIC-CXR', task: 'Multi-label', images: 377110, labels: 14, sizeGb: '295.0', classes: ['No Finding', 'Enlarged Cardiomediastinum', 'Cardiomegaly', 'Lung Opacity', 'Lung Lesion', 'Edema', 'Consolidation', 'Pneumonia', 'Atelectasis', 'Pneumothorax', 'Pleural Effusion', 'Pleural Other', 'Fracture', 'Support Devices'], missingLabels: 44110, duplicates: 2210, trainSplit: 75, valSplit: 12, testSplit: 13, source: 'MIT / Beth Israel', format: 'JPG / DICOM', description: 'Large de-identified critical-care cohort with paired free-text radiology reports.', color: '#10b981' },
  { id: 'vindr', name: 'VinDr-CXR', task: 'Multi-label', images: 18000, labels: 28, sizeGb: '18.4', classes: ['Aortic Aneurysm', 'Atelectasis', 'Calcification', 'Cardiomegaly', 'Clavicle Fracture', 'Consolidation', 'Edema', 'Emphysema', 'Enlarged PA', 'Fibrosis', 'Ill-defined Opacity', 'Infiltration', 'Lung Cyst', 'Lung Tumor', 'Nodule', 'Pleural Effusion', 'Pneumonia', 'Pneumothorax', 'Rib Fracture', 'Scoliosis', 'TB', 'Other'], missingLabels: 60, duplicates: 8, trainSplit: 80, valSplit: 10, testSplit: 10, source: 'VinBrain / Hanoi Medical University', format: 'DICOM / COCO', description: 'Chest X-ray dataset with expert radiologist annotations incl. 22 findings + 6 diseases.', color: '#8b5cf6' },
  { id: 'rsna', name: 'RSNA Pneumonia Detection', task: 'Detection', images: 26684, labels: 1, sizeGb: '9.8', classes: ['Lung Opacity (Pneumonia)'], missingLabels: 0, duplicates: 12, trainSplit: 80, valSplit: 10, testSplit: 10, source: 'RSNA / Kaggle', format: 'DICOM / RLE masks', description: 'Bounding-box detection challenge for pneumonia lung opacities.', color: '#f59e0b' },
];

export const TRAINING_RUNS: TrainingRun[] = [
  { id: 'run-1104d', name: 'swin-b-mixed-precision-amp', model: 'Swin-B', dataset: 'NIH ChestX-ray14', status: 'RUNNING', epoch: 38, totalEpochs: 45, batchSize: 32, lr: '1e-4', optimizer: 'AdamW', scheduler: 'CosineAnnealingLR', loss: 0.104, valLoss: 0.118, valAuroc: 0.889, gpuUtil: 91, startedAt: '2026-07-22', duration: '2d 4h' },
  { id: 'run-1108e', name: 'yolov11-nodule-v3', model: 'YOLOv11', dataset: 'RSNA Pneumonia', status: 'QUEUED', epoch: 0, totalEpochs: 100, batchSize: 16, lr: '1e-3', optimizer: 'SGD Momentum', scheduler: 'ReduceLROnPlateau', loss: 0, valLoss: 0, valAuroc: 0, gpuUtil: 0, startedAt: '—', duration: '—' },
  { id: 'run-1029c', name: 'convnext-base-cosine-lr', model: 'ConvNeXt-Base', dataset: 'CheXpert', status: 'FINISHED', epoch: 60, totalEpochs: 60, batchSize: 64, lr: '5e-5', optimizer: 'AdamW', scheduler: 'CosineAnnealingLR', loss: 0.092, valLoss: 0.108, valAuroc: 0.882, gpuUtil: 94, startedAt: '2026-07-25', duration: '3d 1h' },
  { id: 'run-9943b', name: 'efficientnet-b3-weighted-bce', model: 'EfficientNet-B3', dataset: 'NIH ChestX-ray14', status: 'FINISHED', epoch: 40, totalEpochs: 40, batchSize: 128, lr: '1e-4', optimizer: 'Adam', scheduler: 'StepLR', loss: 0.098, valLoss: 0.121, valAuroc: 0.865, gpuUtil: 88, startedAt: '2026-07-28', duration: '1d 8h' },
  { id: 'run-8821a', name: 'densenet121-focal-loss-v2', model: 'DenseNet-121', dataset: 'VinDr-CXR', status: 'FAILED', epoch: 22, totalEpochs: 50, batchSize: 64, lr: '1e-4', optimizer: 'AdamW', scheduler: 'CosineAnnealingLR', loss: 0.212, valLoss: 0.240, valAuroc: 0.812, gpuUtil: 0, startedAt: '2026-07-30', duration: '11h' },
];

export const EXPLAINABILITY_METHODS = [
  { id: 'gradcam', name: 'Grad-CAM', description: 'Class-discriminative localization from final conv-layer gradients.', filter: 'none', accent: '#6366f1' },
  { id: 'gradcampp', name: 'Grad-CAM++', description: 'Higher-order gradients for fine-grained focal detail.', filter: 'saturate(1.35) contrast(1.1)', accent: '#8b5cf6' },
  { id: 'saliency', name: 'Saliency Map', description: 'Input-gradient magnitude highlighting decisive pixels.', filter: 'grayscale(0.3) contrast(1.6) brightness(1.05)', accent: '#06b6d4' },
  { id: 'integrated', name: 'Integrated Gradients', description: 'Path-integral attribution from black baseline to input.', filter: 'hue-rotate(120deg) saturate(1.5)', accent: '#10b981' },
  { id: 'occlusion', name: 'Occlusion Sensitivity', description: 'Patch-wise perturbation scoring of predictive regions.', filter: 'hue-rotate(300deg) contrast(1.25)', accent: '#f59e0b' },
  { id: 'attention', name: 'Attention Rollout', description: 'Transformer attention head propagation across layers.', filter: 'hue-rotate(200deg) brightness(1.1)', accent: '#ec4899' },
  { id: 'shap', name: 'SHAP', description: 'Game-theoretic Shapley value attribution per input feature.', filter: 'hue-rotate(45deg) saturate(1.6) contrast(1.15)', accent: '#14b8a6' },
  { id: 'lime', name: 'LIME', description: 'Local interpretable surrogate-model explanations on super-pixels.', filter: 'grayscale(0.5) saturate(2) brightness(1.1)', accent: '#fb923c' },
];
